use std::collections::HashMap;
use std::fmt;
use std::sync::OnceLock;

use fastboot_protocol::nusb::NusbFastBoot;

use crate::flash::error::FlashError;
use crate::flash::error::Result;
use crate::flash::transport::FlashTransport;

pub(crate) mod connect;
pub(crate) mod flash;
pub(crate) mod manage;

static EXPECTED_SERIAL: OnceLock<String> = OnceLock::new();

/// Set an expected device serial number to verify against when connecting.
/// When set, `connect()` will filter devices and reject mismatches.
pub fn set_expected_serial(serial: &str) {
    _ = EXPECTED_SERIAL.set(serial.to_string());
}

fn expected_serial() -> Option<&'static str> {
    EXPECTED_SERIAL.get().map(String::as_str)
}

/// Empty vbmeta image with `AVB_FLAGS_NO_AUTH_VERIFICATION` (flags=3).
/// Generated by: `avbtool make_vbmeta_image` --flags 3 --output vendor/empty-vbmeta.img
///
/// Path is anchored at the executor module source file; each `..` resolves
/// to the parent of `src/`.  Moving this file into a deeper subtree would
/// require an additional `..` per additional directory level.
pub(crate) const EMPTY_VBMETA: &[u8] = include_bytes!("../../../../../vendor/empty-vbmeta.img");

/// Reboot target modes understood by fastboot.
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum BootTarget {
    System,
    Bootloader,
    Fastboot,
    Recovery,
}

impl BootTarget {
    #[must_use]
    pub const fn as_str(&self) -> &'static str {
        match self {
            Self::System => "system",
            Self::Bootloader => "bootloader",
            Self::Fastboot => "fastboot",
            Self::Recovery => "recovery",
        }
    }
}

impl fmt::Display for BootTarget {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.as_str())
    }
}

impl std::str::FromStr for BootTarget {
    type Err = String;

    fn from_str(s: &str) -> std::result::Result<Self, Self::Err> {
        match s {
            "system" => Ok(Self::System),
            "bootloader" => Ok(Self::Bootloader),
            "fastbootd" | "fastboot" => Ok(Self::Fastboot),
            "recovery" => Ok(Self::Recovery),
            _ => Err(format!("unknown reboot target '{s}'")),
        }
    }
}

/// Fastboot flash executor.
pub struct FlashExecutor<T: FlashTransport = NusbFastBoot> {
    pub(crate) fb: T,
    device_vars: HashMap<String, String>,
    /// Cached `max-download-size`, queried once per executor lifetime.
    max_download: Option<u32>,
}

impl<T: FlashTransport> FlashExecutor<T> {
    #[must_use]
    pub const fn new(fb: T, device_vars: HashMap<String, String>) -> Self {
        Self { fb, device_vars, max_download: None }
    }

    #[must_use]
    pub const fn device_vars(&self) -> &HashMap<String, String> {
        &self.device_vars
    }

    /// Query `max-download-size` once per executor lifetime and reuse it for
    /// every subsequent flash, avoiding redundant USB round-trips on
    /// multi-target operations (e.g. `--both`).
    async fn max_download(&mut self) -> Result<u32> {
        if let Some(v) = self.max_download {
            return Ok(v);
        }
        let v = parse_max_download(&mut self.fb).await?;
        self.max_download = Some(v);
        Ok(v)
    }
}

/// Query `max-download-size` from the device and validate it is
/// reasonable.  Returns an error if the value is present but below 1 MiB.
pub(crate) async fn parse_max_download(fb: &mut impl FlashTransport) -> Result<u32> {
    let raw = fb.get_var("max-download-size").await.ok();
    let val = raw.as_deref()
        .and_then(|s| fastboot_protocol::protocol::parse_u32(s).ok())
        .unwrap_or(256 * 1024 * 1024);
    if val < 1024 * 1024 {
        return Err(FlashError::ActionFailed {
            partition: "(global)".into(),
            reason: format!("device max-download-size ({val}) is unreasonably small"),
        });
    }
    Ok(val)
}

#[cfg(test)]
mod tests {
    use std::collections::HashMap;
    use serde_json::json;
    use crate::flash::mock::MockTransport;
    use crate::flash::executor::FlashExecutor;
    use crate::flash::progress::FlashRunOptions;
    use crate::scatter_parser::types::{FlashPlan, FlashAction};
    use crate::scatter_parser::types::FlashPlanSummary;

    fn mock_executor() -> FlashExecutor<MockTransport> {
        let fb = MockTransport::new();
        FlashExecutor::new(fb, HashMap::new())
    }

    fn make_action(partition: &str, resolved: Option<&str>) -> FlashAction {
        let image = resolved.map(|p| json!({ "path": { "resolved_path": p } }));
        FlashAction {
            action: "flash".into(),
            partition: partition.into(),
            base_name: String::new(),
            slot: None,
            layout: String::new(),
            region: String::new(),
            start: 0,
            start_hex: String::new(),
            size: 0,
            size_hex: String::new(),
            size_human: String::new(),
            image,
            image_type: None,
            safety_class: String::new(),
            reason: String::new(),
            warnings: Vec::new(),
        }
    }

    fn make_empty_plan(actions: Vec<FlashAction>) -> FlashPlan {
        FlashPlan {
            actions,
            storage_selection: String::new(),
            selected_layouts: Vec::new(),
            platform: None,
            project: None,
            firmware_dir: None,
            package_root: None,
            options: json!({}),
            summary: FlashPlanSummary::default(),
            skipped: Vec::new(),
            incomplete_slots: std::collections::BTreeMap::new(),
            warnings: Vec::new(),
            errors: Vec::new(),
        }
    }

    #[tokio::test]
    async fn execute_plan_happy_path_dry_run() {
        let dir = tempfile::TempDir::new().unwrap();
        let img = dir.path().join("boot.img");
        std::fs::write(&img, b"fake image data").unwrap();
        let mut exec = mock_executor();
        let plan = make_empty_plan(vec![
            make_action("boot", img.to_str()),
        ]);
        let result = exec.execute_plan(
            &plan,
            FlashRunOptions { dry_run: true, ..Default::default() },
        ).await;
        assert_eq!(result.total, 1);
        assert_eq!(result.succeeded, 1);
        assert_eq!(result.failed, 0);
    }

    #[tokio::test]
    async fn execute_plan_missing_image_skipped() {
        let mut exec = mock_executor();
        let plan = make_empty_plan(vec![
            make_action("boot", None),
        ]);
        let result = exec.execute_plan(&plan, FlashRunOptions::default()).await;
        assert_eq!(result.total, 1);
        assert_eq!(result.succeeded, 0);
        assert_eq!(result.failed, 1);
    }

    #[tokio::test]
    async fn execute_plan_download_failure_continues() {
        let dir = tempfile::TempDir::new().unwrap();
        let img = dir.path().join("boot.img");
        std::fs::write(&img, b"fake image data").unwrap();
        let fb = MockTransport::new();
        let mut exec = FlashExecutor::new(fb, HashMap::new());
        exec.fb.fail_download = true;
        let plan = make_empty_plan(vec![
            make_action("boot", img.to_str()),
        ]);
        let result = exec.execute_plan(&plan, FlashRunOptions::default()).await;
        assert_eq!(result.total, 1);
        assert_eq!(result.succeeded, 0);
        assert_eq!(result.failed, 1);
    }

    #[tokio::test]
    async fn execute_plan_dry_run_sends_no_commands() {
        let dir = tempfile::TempDir::new().unwrap();
        let img = dir.path().join("boot.img");
        std::fs::write(&img, b"fake").unwrap();
        let mut exec = mock_executor();
        let plan = make_empty_plan(vec![
            make_action("boot", img.to_str()),
        ]);
        let result = exec.execute_plan(
            &plan,
            FlashRunOptions { dry_run: true, ..Default::default() },
        ).await;
        assert_eq!(result.total, 1);
        assert_eq!(result.succeeded, 1);
        // Only get_var for max-download-size, no download/flash commands
        let cmds = exec.fb.commands();
        assert!(cmds.iter().all(|c| c.starts_with("get_var:")), "dry run should only query vars, got: {cmds:?}");
    }

    #[tokio::test]
    async fn execute_plan_flashes_image_via_direct_read() {
        // Exercises the get_mut_data transfer path (file read directly into
        // the transport buffer) end-to-end against the mock sink.
        let dir = tempfile::TempDir::new().unwrap();
        let img = dir.path().join("boot.img");
        let payload: Vec<u8> = (0..2_000_000u32).map(|i| (i % 251) as u8).collect();
        std::fs::write(&img, &payload).unwrap();
        let mut exec = mock_executor();
        let plan = make_empty_plan(vec![
            make_action("boot", img.to_str()),
        ]);
        let result = exec.execute_plan(&plan, FlashRunOptions::default()).await;
        assert_eq!(result.total, 1);
        assert_eq!(result.succeeded, 1);
        assert_eq!(result.failed, 0);
        let cmds = exec.fb.commands();
        assert!(
            cmds.iter().any(|c| c.starts_with("download:")),
            "expected a download command, got: {cmds:?}",
        );
    }
}
