[package]
name = "pawflash-core"
version.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
base64 = "0.22"
encoding_rs = "0.8"
flate2 = "1.1"
fs4 = "1"
hex = "0.4"
indicatif = "0.17"
inquire = "0.7"
nusb = "0.2"
owo-colors = "4"
quick-xml = "0.38"
rand = "0.8"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"
tabled = { version = "0.18", features = ["derive"] }
tar = "0.4"
miette = { version = "7", features = ["derive"] }
thiserror = "2"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "time", "fs", "io-util", "sync"] }
tokio-serial = "5"
tokio-util = { version = "0.7", features = ["rt"] }
tracing = "0.1"
ureq = "3"
fastboot-protocol = { path = "../../vendor/fastboot-rs/fastboot-protocol" }
android-sparse-image = { path = "../../vendor/fastboot-rs/android-sparse-image" }
penumbra = { git = "https://github.com/ardiandideyashidiq/penumbra", rev = "2a66151efa73c3655ef9b876afa0806714ecd1c5" }
async-trait = "0.1"
strip-ansi-escapes = "0.2"
serde_yaml = { package = "serde_yaml_ng", version = "0.10" }
wincode = "0.5"

[dev-dependencies]
tempfile = "3"
